### ISSUE TITLE
Great Tool

### ISSUE THREAD

**Issue by SimoonTech** [yrtimiD/azure-pipelines-semver-bump#2]
Hi @yrtimiD 

Great tool, however we're trying to get this working but it keeps complaining about:

##[error]Can't increment version: Error: Variable "1" doesn't contains anything. Valid version string was expected.

how do I get this to increment the MajorVersion?
what is needed to put into the Version variable name?

#####
below is my current pipeline setup:

build pipline:

![image](https://user-images.githubusercontent.com/23457220/87533527-a7228580-c68c-11ea-8e90-0f2c26c856b8.png)

variables:

![image](https://user-images.githubusercontent.com/23457220/87533539-aee22a00-c68c-11ea-939d-e8f6ff5ce225.png)

**Comment by yrtimiD** [comment]
two things:
1. "Version variable name" field expects **name** of the variable and not its value. You should pass the name only, without "$(..)", otherwise TFS will feed task with the **current value** of your var.
2. The task group can't work with separated major minor and patch parts variables. (do you really need this separation?)

Not sure this will fit your requirements but try to do next:
* define variable "Version" (or any other name)
* set its value to be "1.0.0" (join your MajorVersion.MinorVersion.PatchVersion)
* put text "Version" (the name of your var, without quotes) into "Version variable name" field.
* select proper value in "Increment level". If you'll keep "patch" - after task executed, value of your Version var will become "1.0.1"

hope this helps

**Comment by SimoonTech** [comment]
Hey man,

thanks for getting back to me so quickly! 

in essence, I would like the build version to be like 1.x.x and increment the MajorVersion each time.

after running the build pipeline with your suggestions I got the following:

#1.0.0.0.0.2

![image](https://user-images.githubusercontent.com/23457220/87536845-a5a78c00-c691-11ea-88a3-54333a0d26eb.png)

**Comment by yrtimiD** [comment]
good, now log says that you passed 1.0.0 and it become 1.0.1. 
Now, if you want to bump **major** version - you should change value in "Increment level" combo to "major":
![image](https://user-images.githubusercontent.com/816805/87547142-58d4ad00-c6b3-11ea-8a04-c53b2aece304.png)
it will make from 1.x.y -> 2.x.y
Still, I don't really understand how you got "1.0.0.0.0.2". Are you doing any extra manipulations after? like re-joining major/minor/patch parts?

**Comment by SimoonTech** [comment]
my current variables is this:

![image](https://user-images.githubusercontent.com/23457220/87547858-a0533d00-c6a3-11ea-880f-177a04d8eaf5.png)

and im only running this one task:
![image](https://user-images.githubusercontent.com/23457220/87547925-b52fd080-c6a3-11ea-9dfd-021ec9ef5806.png)

and here is my build format:
![image](https://user-images.githubusercontent.com/23457220/87547985-ca0c6400-c6a3-11ea-9b3e-15bd75df0662.png)


will this get me the 1.0.0 then 2.0.0 and then 3.0.0?

**Comment by SimoonTech** [comment]
this is what i get back after running the above.
![image](https://user-images.githubusercontent.com/23457220/87548422-62a2e400-c6a4-11ea-912c-fb70133f33e1.png)

**Comment by yrtimiD** [comment]
yes, 
![image](https://user-images.githubusercontent.com/816805/87548640-7440b780-c6b5-11ea-9874-ca037dc8d5a9.png)
this looks better now. 
I would only recommend you to rename MajorVersion to just Version and completely get rid of MajorVersion, MinorVersion, and PatchVersion variables. (usually you should never need these parts separately)
So, in the Build number format you'll have only: `$(Version).$(rev:.r)`

**Comment by SimoonTech** [comment]
update:
build pipeline:
![image](https://user-images.githubusercontent.com/23457220/87549354-9d594c00-c6a5-11ea-9bd7-83cd2b089dcc.png)

variables:
![image](https://user-images.githubusercontent.com/23457220/87549525-d691bc00-c6a5-11ea-927b-3d9c555e6f6d.png)

build props:
![image](https://user-images.githubusercontent.com/23457220/87549566-e5786e80-c6a5-11ea-8962-ff030d9bc398.png)

and this is left as is, unless i need to update anything???

![image](https://user-images.githubusercontent.com/23457220/87549671-05a82d80-c6a6-11ea-83df-e4fbab28243f.png)

**Comment by yrtimiD** [comment]
Right, it's not relevant to task but still:

In azure pipelines Build Number is calculated before build starts and saved into Build.BuildNumber variable. To update it during the build you need to do an extra effort. See [Overwrite build number for your Azure pipeline](https://medium.com/faun/overwrite-build-number-for-your-azure-pipeline-71fd95043f12) as example.
or [How do I update BuildNumber using powershell](https://stackoverflow.com/questions/37046481/how-do-i-update-buildnumber-using-powershell)

**Comment by SimoonTech** [comment]
looking good sir!
thanks for the insight.

![image](https://user-images.githubusercontent.com/23457220/87552732-f9be6a80-c6a9-11ea-9f7b-81f5091c187a.png)

would you know anyway to add the repo name to the end of the build?

i used to have it like this: "2.0.0-beta.178 Updated GitVersion.yml"

is that possible?

**Comment by yrtimiD** [comment]
Check the [list of all predefined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)
The `Build.Repository.Name` might fit...

**Comment by yrtimiD** [comment]
Since the original problem is solved, closing the issue.
Will appreciate if you can [rate](https://marketplace.visualstudio.com/items?itemName=yrtimid.semver-bump-task&ssr=false#review-details) the task :)

**Comment by SimoonTech** [comment]
Hi @yrtimiD I know you closed this issue up but wanted to give you an update, at the moment the Major version is not incrementing is the my current setup.

![image](https://user-images.githubusercontent.com/23457220/87563006-a4d52100-c6b6-11ea-8f93-3731267710ea.png)

![image](https://user-images.githubusercontent.com/23457220/87563054-b3bbd380-c6b6-11ea-9ff0-5e5d2e69ab53.png)

![image](https://user-images.githubusercontent.com/23457220/87563255-eb2a8000-c6b6-11ea-8970-c97ca8f083ff.png)

however 1.0.0 never seems to go to 2.0.0 or 3.0.0 etc... 

its probably something small, but am i missing anything?

as you can see, its never incremented:

![image](https://user-images.githubusercontent.com/23457220/87563585-52e0cb00-c6b7-11ea-8d13-59cafd4964dc.png)

results:

![image](https://user-images.githubusercontent.com/23457220/87563662-668c3180-c6b7-11ea-942d-45bd45cf897b.png)

**Comment by yrtimiD** [comment]
Please check the log of "semver bump" task. you should see there log like: "New version is 2.0.0" - this is to check that task actually incremented version.
But, changing value of $(Version) will not automatically update Build.BuildNumber value which is used in build title you actually want to see. To update title you need to run extra step explained in the links above (https://github.com/yrtimiD/azure-pipelines-semver-bump/issues/2#issuecomment-658763212). Without this new version will stay in "memory" but will not be reflected in the title.
I closed the issue because it's not a task problem, but an overall issue with your build :) discussion is still open.

Update: you can use [Variable Toolbox](https://marketplace.visualstudio.com/items?itemName=jessehouwing.jessehouwing-vsts-variable-tasks) task to update Build.BuildNumber variable with the same template you inserted into the "Build number format" text box. It's an azure pipelines design that forces you to do extra steps.

Update2: btw, you should also think about version persistence. Since your build always starts with version defined in a variable (1.0.0) - the version will remain the same across all builds. You'll need to invent a way to save a new version somewhere (git?) and next time increment previously saved version. Incrementing versions during builds it's always a tricky idea.
